channels:
- conda-forge
dependencies:
- python=3.13.3
- pip<=25.0.1
- pip:
  - mlflow==2.21.2
  - numpy==2.3.2
  - pandas==2.3.2
  - psutil==7.0.0
  - pyarrow==19.0.1
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
